In [1]:
import os
import pandas as pd

# Your API key must be provided, and a project may optionall be selected.
# Use the environment variables already wired up, or overwrite the
# following lines with your own values manually.
API_KEY = os.environ.get('SUST_API_KEY')
PROJECT = os.environ.get('SUST_PROJECT', 'ec-DEMO')

# Identify the name of an existing Climate Explorer portfolio below
PORTFOLIO = 'MRTG_demo'

assert PORTFOLIO, "must set PORTFOLIO"

In [2]:
from sust.api import ClimateExplorerClient

cl = ClimateExplorerClient(API_KEY, PROJECT)

pf = cl.portfolio(PORTFOLIO)
ds = pf.physical_risk_exposure()

pd.DataFrame([{'indicator': ind.name, 'hazard': ind.hazard_name} for ind in ds.indicators])

                   indicator           hazard
0                  obs_score         wildfire
1                  obs_score  flood_potential
2                   obs_freq          cyclone
3           burned_area_norm         wildfire
4   fire_kbdi_susceptibility         wildfire
5          inland_flood_prob  flood_potential
6                  spei_norm     water_stress
7                      score     water_stress
8                     change   sea_level_rise
9                       prob          cyclone
10                      freq         heatwave
11                      temp      fundamental
12                    precip      fundamental
13            extreme_precip      fundamental

In [4]:
ssp = ds.scenarios['ssp245']
win = ds.windows[30]
haz = ds.hazards['wildfire']

sm = ds.summary(ssp, win, haz)

df = pd.DataFrame(sm.to_dicts())
df[df.entity_name == '171']

,risk_class,risk_score,hazard,portfolio_name,portfolio_index,entity_id,entity_name,window,window_start_year,scenario
5,HIGH,0.004346,wildfire,MRTG_demo,5,,171,30,2022,ssp245

In [5]:
ind = ds.indicators['burned_area_norm']

ts = ds.timeseries(ssp, ind)

df = pd.DataFrame(ts.to_dicts())
df[0:10]

,portfolio_name,portfolio_index,entity_id,entity_name,hazard,indicator,scenario,measure,1980,1981,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,MRTG_demo,0,,26,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
1,MRTG_demo,1,,282,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
2,MRTG_demo,2,,227,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
3,MRTG_demo,3,,1664,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
4,MRTG_demo,4,,314,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
5,MRTG_demo,5,,171,wildfire,burned_area_norm,ssp245,mid,0.0,0.000406,...,0.013085,0.006552,0.012343,0.032414,0.00237,0.013705,0.009238,0.033173,0.010271,0.007731
6,MRTG_demo,6,,177,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
7,MRTG_demo,7,,2173,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
8,MRTG_demo,8,,196,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
9,MRTG_demo,9,,2402,wildfire,burned_area_norm,ssp245,mid,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000